# Generated by Django 5.1.5 on 2025-01-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_2',
            field=models.BooleanField(default=False),
        ),
    ]
