# Generated by Django 5.1.5 on 2025-02-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_correct_1_question_correct_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=150),
        ),
    ]
