# Generated by Django 5.1.5 on 2025-01-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lessons.lesson'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
